#BaseURL = ""
#dbaddr = ""
#dbpasswd = ""
#user = ""
#proto = ""
#port = ""
#dbname = ""
#MySQL, SQLite
#dbtype = ""
#mc_server = ""
#allowDefault = false
#defaultUser  = ""
#defaultPassword = ""
#reCAPTCHASiteKey = ""
#reCAPTCHASecret = ""
#reCAPTCHASiteKeyInv = ""
#reCAPTCHASecretInv = ""
#googleOauthConfigClientID = ""
#googleOauthConfigClientSecret = ""
#facebookOauthConfigClientID = ""
#facebookOauthConfigClientSecret = ""


