#BaseURL = ""
#mc_server = ""
#allowDefault = false
#defaultUser  = ""
#defaultPassword = ""
#reCAPTCHASiteKey = ""
#reCAPTCHASecret = ""
#reCAPTCHASiteKeyInv = ""
#reCAPTCHASecretInv = ""
#googleOauthConfigClientID = ""
#googleOauthConfigClientSecret = ""
#facebookOauthConfigClientID = ""
#facebookOauthConfigClientSecret = ""
#registerFromEmailAddress = ""
#registerEmailPasswd = ""
#cookieStoreKey = ""
#AllowAdmin = true
#UseGA = false 
#TinymceAPIKey = ""
#aws_access_key_id = ""
#aws_secret_access_key = ""
#ShowAffiliateLinks = false


