runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: webcontent/\1
  upload: webcontent/favicon.ico\
- url: /images
  static_dir: webcontent/images
- url: /css
  static_dir: webcontent/css
- url: /js
  static_dir: webcontent/js
- url: /.*
  script: _go_app
