#!/bin/bash
export GOPATH='/home/ubuntu/workspace/com.roughindustries.cocktails_go/Packages'
export DBADDR='commonwealthcocktails.c2hmd6oyqsiy.us-east-1.rds.amazonaws.com'
export DBPASSWD='commonwealthcocktails'
export DBUSERNAME='ccuser'
export DBPROTOCOL='tcp'
export DBPORT='3306'
export DBNAME='commonwealthcocktails'
#export  DataSource='Internal'
export DataSource='DB'