package model

var Products = []Product{
	Product{
		ID:          1,
		ProductName: "Orange Juice",
		ProductType: Mixer,
		IsBase:      true,
	},
	Product{
		ID:          2,
		ProductName: "Tropicana™ Orange Juice",
		ProductType: Mixer,
		IsBase:      false,
	},
	Product{
		ID:          3,
		ProductName: "Lemon Juice",
		ProductType: Mixer,
		IsBase:      true,
	},
	Product{
		ID:          4,
		ProductName: "ReaLemon™ Lemon Juice",
		ProductType: Mixer,
		IsBase:      false,
	},
	Product{
		ID:          5,
		ProductName: "Bourbon Whiskey",
		ProductType: Spirit,
		IsBase:      true,
	},
	Product{
		ID:          6,
		ProductName: "Pappy Van Winkle's™ Bourbon Whiskey",
		ProductType: Spirit,
		IsBase:      false,
	},
	Product{
		ID:          7,
		ProductName: "Breckenridge™ Bourbon Whiskey",
		ProductType: Spirit,
		IsBase:      false,
	},
	Product{
		ID:          8,
		ProductName: "Irish Cream Liqueur",
		ProductType: Liqueur,
		IsBase:      true,
	},
	Product{
		ID:          9,
		ProductName: "Bailey's Irish Cream™",
		ProductType: Liqueur,
		IsBase:      false,
	},
	Product{
		ID:          10,
		ProductName: "Hazelnut Liqueur",
		ProductType: Liqueur,
		IsBase:      true,
	},
	Product{
		ID:          11,
		ProductName: "Frangelico™",
		ProductType: Liqueur,
		IsBase:      false,
	},
	Product{
		ID:          12,
		ProductName: "Maple Syrup",
		ProductType: Liqueur,
		IsBase:      true,
	},
	Product{
		ID:          13,
		ProductName: "Stonewall Kitchen™ Maine Maple Syrup",
		ProductType: Liqueur,
		IsBase:      false,
	},
	Product{
		ID:          14,
		ProductName: "Coffee Liqueur",
		ProductType: Liqueur,
		IsBase:      true,
	},
	Product{
		ID:          15,
		ProductName: "Kahlúa™",
		ProductType: Liqueur,
		IsBase:      false,
	},
	Product{
		ID:          16,
		ProductName: "Milk",
		ProductType: Mixer,
		IsBase:      true,
	},
	Product{
		ID:          17,
		ProductName: "Cream",
		ProductType: Mixer,
		IsBase:      true,
	},
	Product{
		ID:          18,
		ProductName: "Coconut Rum",
		ProductType: Spirit,
		IsBase:      true,
	},
	Product{
		ID:          19,
		ProductName: "Malibu™ Coconut Rum",
		ProductType: Spirit,
		IsBase:      false,
	},
	Product{
		ID:          20,
		ProductName: "Amaretto",
		ProductType: Liqueur,
		IsBase:      true,
	},
	Product{
		ID:          21,
		ProductName: "Disaronno™",
		ProductType: Liqueur,
		IsBase:      false,
	},
	Product{
		ID:          22,
		ProductName: "Ginger Root",
		ProductType: Mixer,
		IsBase:      true,
	},
	Product{
		ID:          23,
		ProductName: "Vodka",
		ProductType: Spirit,
		IsBase:      true,
	},
	Product{
		ID:          24,
		ProductName: "Cola",
		ProductType: Mixer,
		IsBase:      true,
	},
}
